### ISSUE TITLE
your readme sounds great

### ISSUE THREAD

**Issue by luxus** [oddlama/nix-config#1]
is it usable for someone else? i'm very interested in kanidm and microvm

**Comment by oddlama** [comment]
Depends on your definition of usable :D

You probably don't want to copy the whole repository because it's quite specific to my machines and needs, but generally you can of course take out all the parts that are useful to you. Most of the stuff is modularized and reasonably self-contained (see `modules/`), so feel free to rip out the parts that you need.

**Comment by oddlama** [comment]
In case you want to build it as-is, you will have to replace the secrets with your own secrets (or use dummy secrets). There are some things like MAC addresses and disk serial numbers that I hid from public view (all the `local.nix.age` files).

**Comment by luxus** [comment]
i will try this weekend i guess.. 
your abstractions is a little i have to read first..
if funny how every advanced config goes very different ways.. it looks like nix still not find the "best" way..

**Comment by oddlama** [comment]
The reusable modules are all just classical nixpkgs-style modules, so if you are familiar with that it should be simple to understand. The only real abstraction layer that is specific to this repository are the "meta" modules which simplify or group some settings for my usecase.

> it looks like nix still not find the "best" way..

I think there isn't a best way. Nix is still just a framework, and the real environment just differs a lot between people. The complexity usually comes from the need to manage multiple machines and intertwining their configs, which is not something you see in nixpkgs or single machine repositories obviously.

I usually do find other people's stuff quite easy to adapt, just 100% copy-pasting is often not what I want.

**Comment by oddlama** [comment]
I'll close this for now. If there's anything else, feel free to answer still

**Comment by luxus** [comment]
i saw that you rewrote the readme. but the how to add a new machine is `incomplete` 
i'm still interested to use this repo maybe as a base for my machines, so i wonder how incomplete is it really?

**Comment by oddlama** [comment]
I only wrote "incomplete" because I didn't write down every step in detail. Basic procedure to add a new host is to copy any existing one, add it to hosts.toml and then it can be built. There's nothing more to it really, I am just to lazy to write a proper chapter in the readme for it :P
