### ISSUE TITLE
Question: Having `wired` as a service

### ISSUE THREAD

**Issue by TornaxO7** [oddlama/nix-config#3]
Hi! I saw that you're using `wired` [as a service](https://github.com/oddlama/nix-config/blob/main/users/myuser/graphical/wired-notify.nix#L8).

May I ask how you're doing it?
The README of `wired-notify` doesn't show how to use the service-variant of `wired` if you're using flakes and home-manager as a nixos-module.

**Comment by oddlama** [comment]
The file you linked is all of the configuration you need. The only other thing is that you have to add the provided overlay and home-manager module to your config:

```nix
nixpkgs.overlays = [
  inputs.wired-notify.overlays.default
];

home-manager.sharedModules = [
    inputs.wired-notify.homeManagerModules.default
];
```

**Comment by TornaxO7** [comment]
may I ask, if you can explain/give me an example how and where I should do this?
```nix
nixpkgs.overlays = [
  inputs.wired-notify.overlays.defaul
];
```
I'm still not really familiar with nix (+ flakes) ecosystem.

# More context
Hint: You don't need to go this further if you don't have time/don't want to do
it. Just close this issue then :)

So here is [my flake]. May I ask what you would change to add the overlay from
`wired` to `nixpkgs`?

[my flake]: https://github.com/TornaxO7/dotfiles/blob/nixos/flake.nix

**Comment by oddlama** [comment]
Basically at the top level of your `configuration.nix` (or any other file that is part of your nixos config). It's [this option](https://search.nixos.org/options?channel=unstable&show=nixpkgs.overlays&from=0&size=50&sort=relevance&type=packages&query=nixpkgs.overlays) that is being set by that.

If this doesn't fully answer your question I would highly recommend you join the [Nix/NixOS Matrix server](https://matrix.to/#/#community:nixos.org), there are always many people online who can help you understand better.

**Comment by TornaxO7** [comment]
Ok, thank you!
