### ISSUE TITLE
modules/kanidm.nix: oidc?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [oddlama/nix-config#5]
hi there!
i was reading thru your kanidm module after hearing about it from @janik-haag. i see it mentions targeting oauth2. i was wondering, would this also include applications using OpenID Connect (OIDC), given that builds upon oauth2? or would the logic differ for the purpose of this module so far?
thanks!

**Comment by oddlama** [comment]
Sure, in kanidm they are just called oauth2 resources, but they should work for both oauth2 and oidc. If I recall correctly I'm actually only using it with OIDC right now :D
