### ISSUE TITLE
Question about the topology module and `nodes.*`

### ISSUE THREAD

**Issue by Ramblurr** [oddlama/nix-config#6]
I hope this is an appropriate place to ask a question about your repo, if not feel free to close.

I was curious about using microvms for running services and via GH search landed in your repo here. 

I notice that in many of your microvm's configs you have a `nodes.sentinel` attribute that seems to "push" some nginx configuration to a different node entirely.

Could you explain a little bit about how that works at a high level? Are there are any articles on that topic you can reference?

**Comment by oddlama** [comment]
> I hope this is an appropriate place to ask a question about your repo, if not feel free to close.

Of course it is :D

> Are there are any articles on that topic you can reference?

To my knowledge nobody has done this before, at least I didn't find anything when I wrote this. I know there are some other approaches like hive.nix which put the modularization on a higher level. This has some advantages regarding generality, but it makes the config more complicated. Now that you mention it, I'll should write a blog post about this :)

> Could you explain a little bit about how that works at a high level?

Of course! My initial idea was to have the relevant nginx configuration for a service (which runs on my "sentinel" proxy server) to be defined by the node that runs the actual service. I do run a lot of stuff at home but I don't want my home IP to leak to the internet, so I use a cloud VPS server (sentinel) that tunnels the request back via wireguard into my home (ward, sire). This has the advantage that I don't need a dynamic DNS service and my traffic is fully encrypted. Basically my own self-made version of cloudflare tunnels, in case you are familiar with those.

Anyway, so at a high level this works by including a [`distributed-config.nix` module](https://github.com/oddlama/nix-config/blob/3e14f82952476814eeb0ed75de60756e87038878/modules/distributed-config.nix) on each node. A node in my configuration is basically what you usually would refer to via `nixosConfigurations`, but including all other dependent nixos configurations, like microvms or nixos-containers.

This module then requires every node to add a new specialArgs attribute called `nodes` which can then be used to access configuration of other nodes.

Assuming we are host1, what the module then does is the following:
- Evaluate `otherNode.config.nodes.host1.services.nginx.virtualHosts` from all other nodes
- Merge those definitions with `mkMerge`
- Assign the merged stuff to it's own `services.nginx.virtualHosts`

This way each node grabs the relevant configuration from each other node. This poses a risk to trigger infinite recursions if used wrongly, so the distributed-config module makes sure to only evaluate some very specific options that I allow to be defined via other nodes (so basically just nginx virtual hosts and firewall rules).

**Comment by oddlama** [comment]
> Question about the topology module

Oh btw none of this has to do with the topology module, so if you have any specific questions about that feel free to ask. That module serves an entirely different purpose. It's a meta module (so nothing that affects your final nixos config in any way), that one can use to generate infrastructure diagrams automatically from multiple node configs. Will be a separate flake in a week or so.

**Comment by oddlama** [comment]
I'm going to close this, feel free to comment if you still have questions.

**Comment by Ramblurr** [comment]
heya @oddlama I have another question for you.

I see that you are using `macvtap` for your microvm guests. In my experience using `macvtap` causes the host to not be able to route to the guest.

Are you running the ingress on a different host (it's difficult for me to untangle that from your repo)? Or is it on the same host as the guest, and if so then how does nginx route to the local guest?

**Comment by oddlama** [comment]
My host can communicate with all guests because it has it's own macvlan interface which is attached to the same physical interface (see hosts/ward/net.nix for example, the real interface is `lan` and the macvlan is `lan-self`). I only assign an ip address to the host via lan-self so it can talk to the guests too.

My actual ingress is running in it's own microvm though, so that wouldn't be strictly required. If you don't want to do this workaround you can also buy a switch that supports hairpin mode, then the packets can be routed back into the port they came from.

**Comment by Ramblurr** [comment]
Ah great that makes sense.

If you don't mind I have some questions about how your ingress/sentinel is actually routing to the correct microvm

Using your forgejo microvm as an example.

On [this line](https://github.com/oddlama/nix-config/blob/main/hosts/ward/guests/forgejo.nix#L26) the `nodes.sentinel = {...}` is actually editing/declaring additional config as if it was done inside `hosts/sentinel` itself.

So on [this line](https://github.com/oddlama/nix-config/blob/main/hosts/ward/guests/forgejo.nix#L49) the upstream address is defined to be the proxy-sentinel wg addr. 

It seems like you are using DHCP for all of the microvm guests. So given the microvm guest ip address can change, how do does nginx route to it? Is your dhcp server handing out static leases?

Edit: Oh i see you have `MulticastDNS = true` in the common guest config, so is nginx using the hostname of the guest? Could you point me to the line where the nginx instance (on sentinel I presume) is configured to do that?

**Comment by oddlama** [comment]
> On [this line](https://github.com/oddlama/nix-config/blob/main/hosts/ward/guests/forgejo.nix#L26) the `nodes.sentinel = {...}` is actually editing/declaring additional config as if it was done inside `hosts/sentinel` itself.

Yes. This is handeled by `modules/distributed-config.nix`, but is otherwise equivalent to specifying it in the other server's config directly. I just wanted to have the related parts together. Honestly it creates some hard to solve infinite recursions sometimes, so it is far from perfect.
 
> So on [this line](https://github.com/oddlama/nix-config/blob/main/hosts/ward/guests/forgejo.nix#L49) the upstream address is defined to be the proxy-sentinel wg addr.

Exactly. I always route everything through wireguard.

> It seems like you are using DHCP for all of the microvm guests. So given the microvm guest ip address can change, how do does nginx route to it? Is your dhcp server handing out static leases?

Both sentinel and the microvm are members of the same wireguard network. If the IP of the microvm changes, the wireguard network will still have static IPs. Wireguard doesn't care if the ip of a client changes, as long as the configured endpoints are reachable. All VMs have the sentinel wireguard server as an endpoint, and keepalive set. So event VMs behind a residential NAT will continue to work when the ISP changes the residential IP overnight.

Nginx always uses the wireguard address of VMs, which is static. So the routing order is the following:

    web request to sentinel:443 -> nginx -> wireguard -> service on VM

> Edit: Oh i see you have `MulticastDNS = true` in the common guest config, so is nginx using the hostname of the guest? Could you point me to the line where the nginx instance (on sentinel I presume) is configured to do that?

I do use mDNS, but there shouldn't be anything actually depending on it. This is coincidental.

**Comment by Ramblurr** [comment]
Thanks for the clarification! That makes sense now that I understand how you're using wireguard. In my impl of this great system (massive props btw) I'll be assigning the microvms ips on my services clan, so I'll just statically assign them to achieve stable routing.

Btw is ward your actual router? That is is the wan iface your actual wan? I've wanted to switch my router from vyos to nixos for awhile. Are you happy with a nixos router?

I also discovered the zone based firewall flake for nftables through your repo, that's a great discovery. Converting all my firewall rules to low level nftables rules was something I didn't want to do...but with that tool now o think I can!

**Comment by oddlama** [comment]
> Thanks for the clarification! That makes sense now that I understand how you're using wireguard. In my impl of this great system (massive props btw) I'll be assigning the microvms ips on my services clan, so I'll just statically assign them to achieve stable routing.
> 
> Btw is ward your actual router? That is is the wan iface your actual wan? I've wanted to switch my router from vyos to nixos for awhile. Are you happy with a nixos router?

If you mean PPPoE, then no. There's still a separate router from my ISP that does the actual DSL stuff. But I guess in principle you can 
 
> I also discovered the zone based firewall flake for nftables through your repo, that's a great discovery. Converting all my firewall rules to low level nftables rules was something I didn't want to do...but with that tool now o think I can!

It has some weird quirks and unclear error messages when you accidentally mistype rule name, but other than that it's a great module!
