### ISSUE TITLE
Question about continuous deployment strategy

### ISSUE THREAD

**Issue by IMax153** [oddlama/nix-config#7]
Hey there @oddlama ! 

I actually found your Nix configs after seeing your post (I think on Reddit) regarding your topology module (super cool stuff by the way).

I've been tweaking my own personal configs for quite some time now, but I still haven't found a piece of tooling that I'm happy with for continuous deployment / integration of the machines I manage with Nix.

I saw in the project README your description of how you bootstrap a new machine. However, I was curious if you could share what strategy you're using to re-deploy after tweaking your configs? Specifically, I'm very interested in how you're coordinating builds.

Cheers!

**Comment by oddlama** [comment]
You might be a bit disappointed, all I'm currently doing is to build on my main machine and deploy from there using the super simple deploy script in `pkgs/deploy.nix` which is added to my devshell. I basically just do `deploy <machine>` to push updates. So I am my build coordination right now :P

I plan to automatically update and build new generations using CI in the future, but my PII secret management scheme is currently preventing me from doing so. I think what I want is to populate a cache automatically but still actually push the updates myself.

**Comment by IMax153** [comment]
> So I am my build coordination right now :P

Hahah - I too am my own build coordination at the moment, but my situation is a bit worse since I have some mismatch in OS / arch between my machines which means in most situations I have to push my code to the remote machine and then build and deploy it there.

I do think the strategy you've gone with using `nodes` to expose information between machines is also super clever.
